# Generated by Django 5.0.13 on 2025-12-13 10:33

import core.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_alter_teamuser_options_teamuser_subdepartment'), ('core', '0003_subdepartment_alter_teamuser_subdepartment'), ('core', '0004_alter_subdepartment_options_and_more'), ('core', '0005_operator_subdepartment_created_at_and_more'), ('core', '0006_calendar_calendar_unique_calendar_per_user_date'), ('core', '0007_pro_prosubdepartment_and_more'), ('core', '0008_alter_pro_options_pro_pro_name_alter_pro_del_date_and_more'), ('core', '0009_operation_routing_routingoperation_and_more'), ('core', '0010_alter_operation_name'), ('core', '0011_alter_pro_status'), ('core', '0012_alter_routing_status'), ('core', '0013_loginoperator'), ('core', '0014_alter_loginoperator_options'), ('core', '0015_alter_loginoperator_options'), ('core', '0016_alter_loginoperator_status'), ('core', '0017_operation_status_routing_declaration_type_and_more'), ('core', '0018_routingoperation_smv_ita'), ('core', '0019_declaration')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdepartment', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subdepartment',
                'verbose_name_plural': 'Subdepartments',
                'ordering': ['subdepartment'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_num', models.CharField(max_length=50, unique=True, verbose_name='Badge Number')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('act', models.BooleanField(default=True, verbose_name='Active')),
                ('pin_code', models.CharField(max_length=20, verbose_name='Pin Code')),
                ('func', models.CharField(max_length=100, verbose_name='Function')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
                'ordering': ['badge_num'],
            },
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('subdepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subdepartment', verbose_name='Subdepartment')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team User',
                'verbose_name_plural': 'Team Users',
                'abstract': False,
            },
            managers=[
                ('objects', core.models.TeamUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('shift_start', models.TimeField(verbose_name='Shift start')),
                ('shift_end', models.TimeField(verbose_name='Shift end')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to=settings.AUTH_USER_MODEL, verbose_name='Team User')),
            ],
            options={
                'verbose_name': 'Calendar entry',
                'verbose_name_plural': 'Calendar',
                'ordering': ['-date', 'team_user__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(fields=('date', 'team_user'), name='unique_calendar_per_user_date'),
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantity')),
                ('del_date', models.DateField(verbose_name='Delivery date')),
                ('status', models.CharField(default='OPEN', max_length=20, verbose_name='Status')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('tpp', models.CharField(max_length=50, verbose_name='TPP')),
                ('skeda', models.CharField(max_length=50, verbose_name='Skeda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PRO',
                'verbose_name_plural': 'PROs',
                'ordering': ['del_date', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='ProSubdepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_subdepartments', to='core.pro', verbose_name='PRO')),
                ('subdepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_subdepartments', to='core.subdepartment', verbose_name='Subdepartment')),
            ],
            options={
                'verbose_name': 'PRO Subdepartment',
                'verbose_name_plural': 'PRO Subdepartments',
            },
        ),
        migrations.AddConstraint(
            model_name='prosubdepartment',
            constraint=models.UniqueConstraint(fields=('pro', 'subdepartment'), name='unique_pro_subdepartment'),
        ),
        migrations.AlterModelOptions(
            name='pro',
            options={'ordering': ['del_date', 'pro_name'], 'verbose_name': 'PRO', 'verbose_name_plural': 'PROs'},
        ),
        migrations.AddField(
            model_name='pro',
            name='pro_name',
            field=models.CharField(default=580000001, max_length=100, unique=True, verbose_name='PRO Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pro',
            name='del_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery date'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='destination',
            field=models.CharField(blank=True, max_length=100, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='skeda',
            field=models.CharField(blank=True, max_length=50, verbose_name='Skeda'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='sku',
            field=models.CharField(blank=True, max_length=100, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='tpp',
            field=models.CharField(blank=True, max_length=50, verbose_name='TPP'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Operation name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Operation description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subdepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.subdepartment', verbose_name='Subdepartment')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
                'ordering': ['subdepartment__subdepartment', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('version_description', models.CharField(blank=True, max_length=255, verbose_name='Version description')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subdepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='core.subdepartment', verbose_name='Subdepartment')),
            ],
            options={
                'verbose_name': 'Routing',
                'verbose_name_plural': 'Routings',
                'ordering': ['sku', 'version'],
            },
        ),
        migrations.CreateModel(
            name='RoutingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_description', models.CharField(blank=True, max_length=255, verbose_name='Operation description')),
                ('smv', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='SMV')),
                ('declaration_type', models.CharField(blank=True, max_length=50, verbose_name='Declaration type')),
                ('final_operation', models.BooleanField(default=False, verbose_name='Final operation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_operations', to='core.operation', verbose_name='Operation')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_operations', to='core.routing', verbose_name='Routing')),
            ],
            options={
                'verbose_name': 'Routing Operation',
                'verbose_name_plural': 'Routing Operations',
                'ordering': ['routing', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='routing',
            constraint=models.UniqueConstraint(fields=('sku', 'subdepartment', 'version'), name='unique_routing_sku_subdep_version'),
        ),
        migrations.AddConstraint(
            model_name='routingoperation',
            constraint=models.UniqueConstraint(fields=('routing', 'operation'), name='unique_routing_operation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Operation name'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='routing',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.CreateModel(
            name='LoginOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_actual', models.DateTimeField(verbose_name='Login actual')),
                ('login_team_date', models.DateField(verbose_name='Login team date')),
                ('login_team_time', models.TimeField(verbose_name='Login team time')),
                ('logoff_actual', models.DateTimeField(blank=True, null=True, verbose_name='Logoff actual')),
                ('logoff_team_date', models.DateField(blank=True, null=True, verbose_name='Logoff team date')),
                ('logoff_team_time', models.TimeField(blank=True, null=True, verbose_name='Logoff team time')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('ERROR', 'ERROR'), ('IGNORE', 'IGNORE')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='core.operator', verbose_name='Operator')),
                ('team_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_users', to=settings.AUTH_USER_MODEL, verbose_name='Team user')),
            ],
            options={
                'verbose_name': 'Login Operator',
                'verbose_name_plural': 'Login Operator',
                'ordering': ['-login_actual'],
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='routing',
            name='declaration_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Declaration type'),
        ),
        migrations.AddField(
            model_name='routing',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Ready'),
        ),
        migrations.AddField(
            model_name='routingoperation',
            name='smv_ita',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='SMV ITA'),
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decl_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Declaration date')),
                ('smv', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='SMV')),
                ('smv_ita', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='SMV ITA')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operators', models.ManyToManyField(blank=True, related_name='declarations', to='core.operator', verbose_name='Operators')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='core.pro', verbose_name='PRO')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='core.routing', verbose_name='Routing')),
                ('routing_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to='core.routingoperation', verbose_name='Routing operation')),
                ('subdepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subdepartment', verbose_name='Subdepartment')),
                ('teamuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to=settings.AUTH_USER_MODEL, verbose_name='Team user')),
            ],
            options={
                'verbose_name': 'Declaration',
                'verbose_name_plural': 'Declarations',
                'ordering': ['-decl_date', 'teamuser__username'],
            },
        ),
    ]
