# Generated by Django 5.0.13 on 2025-12-23 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0019_declaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_name', models.CharField(max_length=100, verbose_name='Break name')),
                ('break_time_start', models.TimeField(verbose_name='Break time start')),
                ('break_time_end', models.TimeField(verbose_name='Break time end')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Break',
                'verbose_name_plural': 'Breaks',
                'ordering': ['break_time_start'],
            },
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='OperatorBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('break_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_breaks', to='core.break', verbose_name='Break')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_breaks', to='core.operator', verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Operator Break',
                'verbose_name_plural': 'Operator Breaks',
                'ordering': ['-date', 'operator'],
            },
        ),
        migrations.AddConstraint(
            model_name='operatorbreak',
            constraint=models.UniqueConstraint(fields=('date', 'operator', 'break_type'), name='unique_operator_break_per_day'),
        ),
    ]
