# Generated by Django 5.0.13 on 2025-12-23 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_break_alter_subdepartment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operatorbreak',
            name='unique_operator_break_per_day',
        ),
        migrations.AddField(
            model_name='operatorbreak',
            name='team_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_operator_breaks', to=settings.AUTH_USER_MODEL, verbose_name='Team user'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='operatorbreak',
            constraint=models.UniqueConstraint(fields=('date', 'operator', 'team_user'), name='unique_operator_break_per_team_day'),
        ),
    ]
