# Generated by Django 5.0.13 on 2026-01-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_operatorbreak_unique_operator_break_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamuser',
            name='team_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Team location'),
        ),
    ]
