# Generated by Django 5.0.13 on 2026-01-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_teamuser_team_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamuser',
            name='login_grace_period',
            field=models.PositiveIntegerField(default=0, help_text='Allowed login delay in minutes', verbose_name='Login grace period (minutes)'),
        ),
    ]
