# Generated by Django 5.0.13 on 2026-01-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_teamuser_login_grace_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginoperator',
            name='break_time',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Break time in minutes', null=True, verbose_name='Break time (minutes)'),
        ),
    ]
