# Generated by Django 5.0.13 on 2026-01-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_loginoperator_break_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtime_name', models.CharField(max_length=100, verbose_name='Downtime name')),
                ('fixed_duration', models.BooleanField(default=False, help_text='If checked, downtime has fixed duration', verbose_name='Fixed duration')),
                ('duration_unit', models.CharField(choices=[('MIN', 'Minutes'), ('HOUR', 'Hours'), ('SHIFT', 'Per shift')], max_length=10, verbose_name='Duration unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subdepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='core.subdepartment', verbose_name='Subdepartment')),
            ],
            options={
                'verbose_name': 'Downtime',
                'verbose_name_plural': 'Downtimes',
                'ordering': ['subdepartment__subdepartment', 'downtime_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='downtime',
            constraint=models.UniqueConstraint(fields=('downtime_name', 'subdepartment'), name='unique_downtime_name_per_subdepartment'),
        ),
    ]
