# Generated by Django 5.0.13 on 2026-01-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_downtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downtime',
            name='duration_unit',
        ),
        migrations.AddField(
            model_name='downtime',
            name='downtime_value',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes. Required if fixed duration is enabled.', null=True, verbose_name='Downtime value (minutes)'),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='fixed_duration',
            field=models.BooleanField(default=False, help_text='If checked, downtime has fixed duration in minutes', verbose_name='Fixed duration'),
        ),
    ]
