# Generated by Django 5.0.13 on 2026-01-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_downtime_duration_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='downtime_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration in minutes (e.g. 2.50). Required if fixed duration is enabled.', max_digits=6, null=True, verbose_name='Downtime value (minutes)'),
        ),
    ]
