# Generated by Django 5.0.13 on 2026-01-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_downtime_downtime_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtime_value', models.DecimalField(decimal_places=2, help_text='Single downtime duration in minutes', max_digits=6, verbose_name='Downtime value (minutes)')),
                ('repetition', models.PositiveIntegerField(default=1, help_text='Number of repetitions', verbose_name='Repetition')),
                ('downtime_total', models.DecimalField(decimal_places=2, editable=False, max_digits=8, verbose_name='Total downtime (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtime_declarations', to='core.downtime', verbose_name='Downtime')),
                ('login_operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtime_declarations', to='core.loginoperator', verbose_name='Login operator')),
            ],
            options={
                'verbose_name': 'Downtime Declaration',
                'verbose_name_plural': 'Downtime Declarations',
                'db_table': 'core_downtimedeclaration',
                'ordering': ['-created_at'],
            },
        ),
    ]
