"""
Django settings for project.

Generated by 'django-admin startproject' using Django 5.0.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DJANGO_ENV = config('DJANGO_ENV', default='dev')
DEBUG = config('DEBUG', cast=bool, default=False)

_force_script = config('FORCE_SCRIPT_NAME', default='')
FORCE_SCRIPT_NAME = _force_script or None

STATIC_URL = config('STATIC_URL', default='/static/')
SESSION_COOKIE_PATH = config('SESSION_COOKIE_PATH', default='/')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^thr6bgy-&-ylmw7r(j)k8c8($9q+6lyd!qw5ecifjl9$yeyou'


ALLOWED_HOSTS = ['172.27.161.193', 'localhost', '127.0.0.1']

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',

    'core',
    'planners',
    'teams',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # "core.context_processors.user_roles",
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
     'default': {
        'ENGINE': 'mssql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes',
        }
     },
    'inteos': {
        'ENGINE': 'mssql',
        'NAME': config('DB_NAME_INTEOS'),
        'USER': config('DB_USER_INTEOS'),
        'PASSWORD': config('DB_PASSWORD_INTEOS'),
        'HOST': config('DB_HOST_INTEOS'),
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes',
        }
    },
    'posummary': {
        'ENGINE': 'mssql',
        'NAME': config('DB_NAME_POSUM'),
        'USER': config('DB_USER_POSUM'),
        'PASSWORD': config('DB_PASSWORD_POSUM'),
        'HOST': config('DB_HOST_POSUM'),
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes',
        }
    }


}

AUTH_USER_MODEL = 'core.TeamUser'

# Set the user session expiration time
SESSION_COOKIE_AGE = 365 * 24 * 60 * 60  # 365 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Don't expire session when browser is closed


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
AUTH_PASSWORD_VALIDATORS = []

# settings.py
LOGIN_URL = '/login'  # Or the URL you prefer
LOGIN_REDIRECT_URL = ''

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Europe/Belgrade'
TIME_FORMAT = 'H:i'
DATE_FORMAT = "d.m.Y"
DATETIME_FORMAT = "d.m.Y H:i"

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Admin input format (za DateInput i DateTimeInput)
DATE_INPUT_FORMATS = ["%d.%m.%Y."]
DATETIME_INPUT_FORMATS = ["%d.%m.%Y. %H:%M"]
TIME_INPUT_FORMATS = ["%H:%M"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/



STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Path to the project directory
BASE_DIR = Path(__file__).resolve().parent.parent

STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",        # Static files for core
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# INTERNAL_IPS = [
#     '127.0.0.1',
# ]

SESSION_COOKIE_NAME = 'prep_sessionid'
